2018-08-05 12:50:17,980 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2018-08-05 12:50:17,986 [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 2269
2018-08-05 12:50:47,855 [views:list_vip_person] [INFO]- 【VIP人员接口数据】：{"msg": "", "count": 13, "code": 0, "data": [{"vip_phone": "17555551212", "vip_notes": "1", "vip_name": "\u62db\u65b0", "vip_person_point": 0, "id": 35, "vip_sex": "\u7537"}, {"vip_phone": "17658584445", "vip_notes": "", "vip_name": "1761111", "vip_person_point": 0, "id": 34, "vip_sex": "\u5973"}, {"vip_phone": "17658585844", "vip_notes": "1", "vip_name": "17658585888", "vip_person_point": 0, "id": 33, "vip_sex": "\u7537"}, {"vip_phone": "17658585881", "vip_notes": "17658585888", "vip_name": "12", "vip_person_point": 0, "id": 32, "vip_sex": "\u7537"}, {"vip_phone": "17658585888", "vip_notes": "1", "vip_name": "1", "vip_person_point": 0, "id": 31, "vip_sex": "\u7537"}, {"vip_phone": "17629298888", "vip_notes": "1", "vip_name": "1", "vip_person_point": 0, "id": 29, "vip_sex": "\u7537"}, {"vip_phone": "18620010342", "vip_notes": "fsfsafafe2", "vip_name": "fsdfgafg111111", "vip_person_point": 0, "id": 26, "vip_sex": "\u7537"}, {"vip_phone": "18620010341", "vip_notes": "fafa", "vip_name": "fsfsf", "vip_person_point": 0, "id": 25, "vip_sex": "\u7537"}, {"vip_phone": "17655551111", "vip_notes": "", "vip_name": "1", "vip_person_point": 0, "id": 24, "vip_sex": "\u7537"}, {"vip_phone": "14544445444", "vip_notes": "", "vip_name": "\u725b", "vip_person_point": 0, "id": 21, "vip_sex": "\u7537"}]}
2018-08-05 12:50:47,855 [basehttp:log_message] [INFO]- "GET /listVipPerson/?page=1&limit=10 HTTP/1.1" 200 1304
